### ISSUE TITLE
Onboard @MartinDelille

### ISSUE THREAD

**Issue by Changaco** [liberapay/salon#7]
Hey @MartinDelille, welcome! Any questions about Liberapay's source code or something else? You can ask them here. :-)

**Comment by MartinDelille** [comment]
:+1: I'll be happy to contribute and might need some help!

I will try to start with some [easy](https://github.com/liberapay/liberapay.com/labels/Easy) issue like this one: liberapay/liberapay.com#49

**Comment by Changaco** [comment]
I've invited you into the GitHub org so you can create branches directly into the official repository instead of using a fork.

**Comment by MartinDelille** [comment]
Thanks I feel very proud! I started reading the code and it is very clean and easy to read.

**Comment by Changaco** [comment]
I've invited you into the Liberapay team as well. :-)

**Comment by Changaco** [comment]
> I started reading the code and it is very clean and easy to read.

Thanks, I've worked hard on that ever since I started working on then Gittip.

By the way, did you find the README helpful in setting up a local dev environment? Do you have improvement suggestions?

**Comment by MartinDelille** [comment]
Yes it was very clear! Maybe the only step would be about *postgresql* setup. I'm almost new to this database but already installed it for [another project](http://exercism.io/) and had some conflict (I finally remove the */usr/local/var/folder* and redo the init).

**Comment by Changaco** [comment]
What kind of conflict?

Now that I think about it, one info missing about postgres is that it needs to be version 9.4 (preferably 9.4.5, but the previous 9.4.x versions should also work I suppose).

**Comment by MartinDelille** [comment]
Not a conflict, a user right issue in fact. I have no *postgres* user (but a *_postgrey*) on my OSX. I had an error modifying the */usr/local/var/folder* so deleting it solved the problem. I did this quickly and don't remember exactly. In the end, my regular user was already allowed to create the db.

**Comment by MartinDelille** [comment]
I'm facing a new problem now: I'm unable to loggin anymore on my local env. I tried to reset my config without success. The problem is the following: I create a new account and when I click *Go* the form is just reset.

**Comment by Changaco** [comment]
Did you `git pull` after liberapay/liberapay.com#129 was merged?

**Comment by MartinDelille** [comment]
Yes. I thought it was solved because I create account on the https://liberapay.com page instead of my local so we have 3 new fake accounts (martin, capradmar and chapi).

**Comment by Changaco** [comment]
I've closed the accounts, I'll see later about removing them from the DB entirely.

**Comment by MartinDelille** [comment]
Ok I test on another browser and I can login. This may be related to cookie and #106.

**Comment by Changaco** [comment]
Is the branch you're on really based on the current master? If you're not on master and you didn't do a `git rebase master` then it's normal that you're still encountering the sign-in bugs.

**Comment by MartinDelille** [comment]
No I tested it on master with your latest commit in the log. I'm using Chrome on OSX.

**Comment by Changaco** [comment]
!m @MartinDelille (["!m" means "You're doing good work!"](http://motivate.im/))

**Comment by Changaco** [comment]
@MartinDelille What are you planning to work on next? You shouldn't take all the Easy issues, it's better to leave some for future newcomers. ;-)

**Comment by MartinDelille** [comment]
I'm very interested into [cucumber](https://cucumber.io/) these times. Do you think it would be interesting to add cucumber specs to liberapay? This is quite big work I think, but might be interesting for the future.

Otherwise I'll be happy to increase the code coverage by solving bugs with the *Bug prevention* tag.

I thought also about adding a [shield.io](badge) for Github project (even if I don't have any idea of how to set this up).

**Comment by Changaco** [comment]
I'm not opposed to trying out cucumber, if you can show that it would be better than what we have now I would approve switching to it.

However I'm more interested in concrete short-term improvements, so if you want to take on some Bug Prevention issues that's great.

I'm not sure what you mean by "adding a badge for Github project".

**Comment by MartinDelille** [comment]
Regarding liberapay/liberapay.com#183, I didn't really get where do I need to change bootstrap color? Can you give me an entry point?

**Comment by Changaco** [comment]
We don't have our own script to build Bootstrap, so if you want to change its variables you have to go on https://getbootstrap.com/customize/ and download a custom build from there, then replace the one currently in liberapay. Obviously, it would be better to integrate Bootstrap so that we can easily change its variables.

**Comment by MartinDelille** [comment]
I didn't figured out how bootstrap is integrated (I'm not very good at web development but I think with a little help I can manage to do it)

**Comment by MartinDelille** [comment]
Other subject: I develop in Swift and I wondered if it'll be possible to develop an iOS app. Do you think the backend would be ready for that?

**Comment by Changaco** [comment]
I can't precisely tell you how to integrate Bootstrap into Liberapay since I've never integrated Bootstrap before, but basically it involves compiling it ourselves, maybe from the SASS source like our own styles.

As for mobile apps, we have some endpoints that can return JSON, but probably not enough. We support HTTP's Basic auth, but we're not an OAuth provider, so right now the app would have to store the user's permanent password (we could probably add a simple system of tokens, which would be a first step towards OAuth).

**Comment by MartinDelille** [comment]
I'm think of a simple viewer at the beginning. The idea is to enable the possibility to have Liberapay in its pocket that make more easy to speak about it since we're not always in front of a computer. I'll create the repository as soon as I'll have something.

**Comment by MartinDelille** [comment]
Could you tell me for example what is the endpoint for listing Liberapay users?

**Comment by Changaco** [comment]
We don't have one, you can search users but not list them all. Related issue: https://github.com/liberapay/liberapay.com/issues/297.

Wouldn't improving the responsiveness of the website be easier and more effective at reaching mobile users than developing native apps?

**Comment by MartinDelille** [comment]
Like I said I'm very bad at web development so I won't be able to help so
much. For me it's also a good entry point for entering liberapay's code
base which is huge. I'll try to make a quick prototype and will see if
there is some interest to push it forward.
Le jeu. 21 juil. 2016 à 10:31, Charly C. <notifications@github.com> a
écrit :

**Comment by MartinDelille** [comment]
As a first prototype, I would like to make something very simple: just a single screen displaying the current homepage equivalent:

```
Liberapay is a recurrent donations platform.
Learn more / Follow us
We currently have 485 users donating €1,526.03 per month.
```

What would be the endpoint for the users number and the amount of money donated per month?

**Comment by Changaco** [comment]
You have to learn to figure this stuff out yourself, the only tool you need is `git grep`. By searching for "We currently have", or by looking directly at the source code for the homepage, you can find [this line](https://github.com/liberapay/liberapay.com/blob/6bdacfb8d6d2b05d28e9ae5a4a53479d9f187ede/www/index.html.spt#L78) which gives you the names of the variables, then by grepping for those names you can see that `gmonthly_volume` isn't available anywhere, but `gnusers` is available as `nusers` in [/about/stats.json](https://liberapay.com/about/stats.json).

**Comment by MartinDelille** [comment]
Thanks! This is the kickstart I needed :-)

**Comment by MartinDelille** [comment]
First draft: https://github.com/liberapay/liberapay-ios

**Comment by MartinDelille** [comment]
I wanted to set back my dev environment with Docker but I'm blocked by this issue: https://github.com/liberapay/liberapay.com/issues/1204

**Comment by MartinDelille** [comment]
@Changaco How do we comment in Aspen simplate language?

**Comment by Changaco** [comment]
There are no simplate-level comments, instead comments should be included in the simplate's pages using the syntax of the embedded language: `# …` for python, `{# … #}` for jinja, etc.

**Comment by MartinDelille** [comment]
Anyway I didn't contribute to the code since a long time and I found it very easy to do so!

I would need your help to think about how we will achieve to fix https://github.com/liberapay/liberapay.com/issues/353 (PR on its way: https://github.com/liberapay/liberapay.com/pull/1220).

Currently I only touch to the UI.

**Comment by MartinDelille** [comment]
Could you add me to the freshdesk? Support is part of my daily job so I can be some help here. I don't know if using Freshdesk for support is still in the plan. I studied other alternative I think the best is https://about.gitlab.com/product/service-desk/ but I have to check if it works for opensource project (having support discussion public on the internet can be a problem although).

**Comment by MartinDelille** [comment]
Hi @Changaco,

I wanted to set back my development environment but I have a problem when executing `make schema` on the current `master` branch:

```
$ make schema
env/bin/honcho run -e defaults.env,local.env ./recreate-schema.sh
make: env/bin/honcho: No such file or directory
make: *** [schema] Error 1
```

Any idea?

**Comment by Changaco** [comment]
Have you tried `make clean env`?

**Comment by MartinDelille** [comment]
It fails at a given time:

```
$ make clean env
...
Collecting wrapt==1.11.0 (from -r requirements_tests.txt (line 117))
  Using cached https://files.pythonhosted.org/packages/78/4d/c3f9bd791683bd61b7799e465872bf5f4495fe3abb6c4f119419b9f606eb/wrapt-1.11.0.tar.gz
Collecting fake-factory==0.3.2 (from -r requirements_tests.txt (line 144))
  Using cached https://files.pythonhosted.org/packages/de/38/748a54953a65fbb970d5619bef360819ab7f8cd5d3fbbb5092df03dde01f/fake-factory-0.3.2.tar.gz
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer==0.1.13->-r requirements_base.txt (line 196))
Collecting enum34; python_version < "3" (from cryptography==2.4.2->-r requirements_base.txt (line 220))
Requirement already satisfied: setuptools in ./env/lib/python2.7/site-packages (from pytest==3.6.4->-r requirements_tests.txt (line 1)) (40.8.0)
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" from https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl#sha256=ec0a6cb848cc212002b9828c3e34c675e0c9ff6741dc445cab6fdd4e1085d1f1 (from s3transfer==0.1.13->-r requirements_base.txt (line 196))
    enum34; python_version < "3" from https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl#sha256=6bd0f6ad48ec2aa117d3d141940d484deccda84d4fcd884f5c3d93c23ecd8c79 (from cryptography==2.4.2->-r requirements_base.txt (line 220))
make: *** [env] Error 1
```

**Comment by Changaco** [comment]
That's <https://github.com/liberapay/liberapay.com/issues/1435>.

**Comment by MartinDelille** [comment]
Ok I realized I wasn't on the latest master revision: my master track the gitlab master branch because I'm doing a manual mirror operation (there might be [a way automate this](https://github.com/liberapay/liberapay.com/issues/1448).

I still have an issue:

```
$ make clean env
...
ollecting fake-factory==0.3.2 (from -r requirements_tests.txt (line 144))
  Using cached https://files.pythonhosted.org/packages/de/38/748a54953a65fbb970d5619bef360819ab7f8cd5d3fbbb5092df03dde01f/fake-factory-0.3.2.tar.gz
Requirement already satisfied: setuptools in ./env/lib/python3.7/site-packages (from pytest==3.6.4->-r requirements_tests.txt (line 1)) (39.1.0)
THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    MarkupSafe==1.1.0 from https://files.pythonhosted.org/packages/96/52/eef455862764cb6d6c136aa52c7f9fc4e7c1c644790a7107b1244a2b8a53/MarkupSafe-1.1.0-cp37-cp37m-macosx_10_6_intel.whl#sha256=1f19ef5d3908110e1e891deefb5586aae1b49a7440db952454b4e281b41620cd (from -r requirements_base.txt (line 41)):
        Expected sha256 efdc45ef1afc238db84cb4963aa689c0408912a0239b0721cb172b4016eb31d6
        Expected     or 52ccb45e77a1085ec5461cde794e1aa037df79f473cbc69b974e73940655c8d7
        Expected     or 525396ee324ee2da82919f2ee9c9e73b012f23e7640131dd1b53a90206a0f09c
        Expected     or 5c3fbebd7de20ce93103cb3183b47671f2885307df4a17a0ad56a1dd51273d36
        Expected     or f82e347a72f955b7017a39708a3667f106e6ad4d10b25f237396a7115d8ed5fd
        Expected     or 31cbb1359e8c25f9f48e156e59e2eaad51cd5242c05ed18a8de6dbe85184e4b7
        Expected     or edce2ea7f3dfc981c4ddc97add8a61381d9642dc3273737e756517cc03e84dd6
        Expected     or bf54103892a83c64db58125b3f2a43df6d2cb2d28889f14c78519394feb41492
        Expected     or 048ef924c1623740e70204aa7143ec592504045ae4429b59c30054cb31e3c432
        Expected     or 83381342bfc22b3c8c06f2dd93a505413888694302de25add756254beee8449c
        Expected     or 130f844e7f5bdd8e9f3f42e7102ef1d49b2e6fdf0d7526df3f87281a532d8c8b
        Expected     or 52b07fbc32032c21ad4ab060fec137b76eb804c4b9a1c7c7dc562549306afad2
        Expected     or 4e97332c9ce444b0c2c38dd22ddc61c743eb208d916e4265a2a3b575bdccb1d3
             Got        1f19ef5d3908110e1e891deefb5586aae1b49a7440db952454b4e281b41620cd

    libsass==0.17.0 from https://files.pythonhosted.org/packages/a0/60/d1332c95d149d8e4976208e8bb6db39a0746b6ee46e94d840da3a0b05629/libsass-0.17.0-cp37-cp37m-macosx_10_14_x86_64.whl#sha256=1aeadc155594af23879e27792667dc06e7f248c2c599c40ff2a7335193abdf05 (from -r requirements_base.txt (line 125)):
        Expected sha256 bf6b7ad08f287695338f050c80f79d258a405e5c349cdaeb9be5d5376c09e37a
        Expected     or 0da943e00e028211cb4bb91496a20becab9fe82407bb75266ec4212af04acb45
        Expected     or 411833c623288138744865d882f5226f6db52afce1e19f42722c416df9d308dc
        Expected     or 66e3062ff508c81928e35c66702f0cc4f70fb12eb76ba23eeb0ff87a6340cc13
        Expected     or a19041e78d5bb7c5d72e010e893c29119693628b6ee06025503ab2584cf24edd
        Expected     or 107591ba2c0d173bb1705bef0e9fd04a5b6f482f3584f4ea51b28ab8b137fbb2
        Expected     or 4bf7a80a956da9de9715436b85343a179da4ff399a6e9a1694e70bff93d43099
        Expected     or 55b77204cfa363142ab02c49ee871321a396b8e51f6361ebc226c3953c780541
        Expected     or 953ebe810f09d81b84ccafdca0fb6171d1b58c8f0147cb650184a41e124e296f
             Got        1aeadc155594af23879e27792667dc06e7f248c2c599c40ff2a7335193abdf05

    coverage==4.5.2 from https://files.pythonhosted.org/packages/be/88/7e5e548329eda1f003b3ff34e57ba6b2b1f8b8983043e99a0ecf58ae0a06/coverage-4.5.2-cp37-cp37m-macosx_10_13_x86_64.whl#sha256=d64b4340a0c488a9e79b66ec9f9d77d02b99b772c8b8afd46c1294c1d39ca478 (from -r requirements_tests.txt (line 35)):
        Expected sha256 b3b0c8f660fae65eac74fbf003f3103769b90012ae7a460863010539bb7a80da
        Expected     or 8cb4febad0f0b26c6f62e1628f2053954ad2c555d67660f28dfb1b0496711952
        Expected     or 447c450a093766744ab53bf1e7063ec82866f27bcb4f4c907da25ad293bba7e3
        Expected     or 1b4276550b86caa60606bd3572b52769860a81a70754a54acc8ba789ce74d607
        Expected     or 6694d5573e7790a0e8d3d177d7a416ca5f5c150742ee703f3c18df76260de794
        Expected     or 510986f9a280cd05189b42eee2b69fecdf5bf9651d4cd315ea21d24a964a3c36
        Expected     or 09e47c529ff77bf042ecfe858fb55c3e3eb97aac2c87f0349ab5a7efd6b3939f
        Expected     or 5535dda5739257effef56e49a1c51c71f1d37a6e5607bb25a5eee507c59580d1
        Expected     or 0cc941b37b8c2ececfed341444a456912e740ecf515d560de58b9a76562d966d
        Expected     or da969da069a82bbb5300b59161d8d7c8d423bc4ccd3b410a9b4d8932aeefc14b
        Expected     or 6831e1ac20ac52634da606b658b0b2712d26984999c9d93f0c6e59fe62ca741b
        Expected     or 5f55028169ef85e1fa8e4b8b1b91c0b3b0fa3297c4fb22990d46ff01d22c2d6c
        Expected     or 10e8af18d1315de936d67775d3a814cc81d0747a1a0312d84e27ae5610e313b0
        Expected     or aaa0f296e503cda4bc07566f592cd7a28779d433f3a23c48082af425d6d5a78f
        Expected     or 1e8a2627c48266c7b813975335cfdea58c706fe36f607c97d9392e61502dc79d
        Expected     or 46101fc20c6f6568561cdd15a54018bb42980954b79aa46da8ae6f008066a30e
        Expected     or ee5b8abc35b549012e03a7b1e86c09491457dba6c94112a2482b18589cc2bdb9
        Expected     or c45297bbdbc8bb79b02cf41417d63352b70bcb76f1bbb1ee7d47b3e89e42f95d
        Expected     or ab235d9fe64833f12d1334d29b558aacedfbca2356dfb9691f2d0d38a8a7bfb4
        Expected     or 99bd767c49c775b79fdcd2eabff405f1063d9d959039c0bdd720527a7738748a
        Expected     or 71afc1f5cd72ab97330126b566bbf4e8661aab7449f08895d21a5d08c6b051ff
        Expected     or 7349c27128334f787ae63ab49d90bf6d47c7288c63a0a5dfaa319d4b4541dd2c
        Expected     or 859714036274a75e6e57c7bab0c47a4602d2a8cfaaa33bbdb68c8359b2ed4f5c
        Expected     or 0d34245f824cc3140150ab7848d08b7e2ba67ada959d77619c986f2062e1f0e8
        Expected     or 3ad59c84c502cd134b0088ca9038d100e8fb5081bbd5ccca4863f3804d81f61d
             Got        d64b4340a0c488a9e79b66ec9f9d77d02b99b772c8b8afd46c1294c1d39ca478

    multidict==4.5.2 from https://files.pythonhosted.org/packages/0e/64/39b167d63e292cc2336d09c4d3577089db82cd7886ed535b6100fc7c7966/multidict-4.5.2-cp37-cp37m-macosx_10_12_intel.macosx_10_12_x86_64.macosx_10_13_intel.macosx_10_13_x86_64.whl#sha256=1d48bc124a6b7a55006d97917f695effa9725d05abe8ee78fd60d6588b8344cd (from -r requirements_tests.txt (line 127)):
        Expected sha256 068167c2d7bbeebd359665ac4fff756be5ffac9cda02375b5c5a7c4777038e73
        Expected     or 7c1b7eab7a49aa96f3db1f716f0113a8a2e93c7375dd3d5d21c4941f1405c9c5
        Expected     or 8ccd1c5fff1aa1427100ce188557fc31f1e0a383ad8ec42c559aabd4ff08802d
        Expected     or 6a3a9b0f45fd75dc05d8e93dc21b18fc1670135ec9544d1ad4acbcf6b86781d0
        Expected     or 31dfa2fc323097f8ad7acd41aa38d7c614dd1960ac6681745b6da124093dc351
        Expected     or 8e08dd76de80539d613654915a2f5196dbccc67448df291e69a88712ea21e24a
        Expected     or d1071414dd06ca2eafa90c85a079169bfeb0e5f57fd0b45d44c092546fcd6fd9
        Expected     or db603a1c235d110c860d5f39988ebc8218ee028f07a7cbc056ba6424372ca31b
        Expected     or ce20044d0317649ddbb4e54dab3c1bcc7483c78c27d3f58ab3d0c7e6bc60d26a
        Expected     or 4b843f8e1dd6a3195679d9838eb4670222e8b8d01bc36c9894d6c3538316fa0a
        Expected     or 047c0a04e382ef8bd74b0de01407e8d8632d7d1b4db6f2561106af812a68741b
        Expected     or 148ff60e0fffa2f5fad2eb25aae7bef23d8f3b8bdaf947a65cdbe84a978092bc
        Expected     or 4b02a3b2a2f01d0490dd39321c74273fed0568568ea0e7ea23e02bd1fb10a10b
        Expected     or d3be11ac43ab1a3e979dac80843b42226d5d3cccd3986f2e03152720a4297cd7
        Expected     or 024b8129695a952ebd93373e45b5d341dbb87c17ce49637b34000093f243dd4f
             Got        1d48bc124a6b7a55006d97917f695effa9725d05abe8ee78fd60d6588b8344cd

make: *** [env] Error 1
```

I'm not an expert but it looks like the hashes are missing for this python version right?

**Comment by MartinDelille** [comment]
I tried with the `docker-compose build` command which is also failing:

```
$ docker-compose build
...
Collecting asn1crypto==0.24.0 (from -r /requirements/pip/base.txt (line 243))
  Downloading https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer==0.1.13->-r /requirements/pip/base.txt (line 202))
Collecting enum34; python_version < "3" (from cryptography==2.4.2->-r /requirements/pip/base.txt (line 226))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" from https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl#sha256=ec0a6cb848cc212002b9828c3e34c675e0c9ff6741dc445cab6fdd4e1085d1f1 (from s3transfer==0.1.13->-r /requirements/pip/base.txt (line 202))
    enum34; python_version < "3" from https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl#sha256=6bd0f6ad48ec2aa117d3d141940d484deccda84d4fcd884f5c3d93c23ecd8c79 (from cryptography==2.4.2->-r /requirements/pip/base.txt (line 226))
ERROR: Service 'web' failed to build: The command '/bin/sh -c pip install --require-hashes -r /requirements/pip/base.txt' returned a non-zero code: 1
```

I know that Docker is not really officially supported (and I would prefer not to use it by the way) but it was just to test another option to bring back my dev environment up.
